# Generated by Django 4.2.1 on 2023-06-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_houses_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('floors', models.TextField(choices=[('floor 1', 'floor 1'), ('floor 2', 'floor 2'), ('floor 3', 'floor3'), ('floor 4', 'floor 4')])),
                ('amount', models.FloatField(max_length=100)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.customer')),
            ],
        ),
    ]
