# Generated by Django 4.2.1 on 2023-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date_booked',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='floors',
            field=models.TextField(choices=[('first floor', 'first floor'), ('second floor', 'second floor'), ('third floor', 'third floor'), ('fourth floor', 'fourth floor')]),
        ),
    ]
