# Generated by Django 4.2.1 on 2023-06-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_checkout_date_booked_alter_checkout_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='name',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='date_booked',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
