# Generated by Django 4.2.1 on 2023-06-30 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0009_alter_checkout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.ForeignKey(blank=True,  null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
