# Generated by Django 4.2.1 on 2023-07-01 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0011_remove_checkout_name_checkout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='houses',
            name='name',
            field=models.CharField(blank=True, choices=[('bedsitter', 'one bedsitter'), ('two bedroom', 'two bedroom'), ('three bedroom', 'three bedroom'), ('four bedroom', 'four bedroom')], max_length=100, null=True),
        ),
    ]
